---
- name: Installng Xfce Packages
  dnf: 
    name: ['@Xfce-Desktop'] 
    state: present
  become: yes

- name: Installing light-locker
  dnf:
    name: ['light-locker']
    state: present
  become: yes

- name: Removing xscreensaver
  dnf:
    name: ['xscreensaver']
    state: absent
  become: yes

- name: Setting light-locker lockCommand
  command: xfconf-query -c xfce4-session -p /general/LockCommand -s "light-locker-command -l" --create -t string

